[project]
authors = [
  {name = "Justin Flannery", email = "juftin@juftin.com"}
]
license = "MIT"
name = "cookiecutter-python"
readme = "README.md"
requires-python = ">=3.10"
version = "1.0.0"

[dependency-groups]
dev = [
  "copier~=9.0",
  "pytest",
  "pytest-cov"
]
docs = [
  "mkdocs~=1.5.2",
  "mkdocs-material~=9.2.3",
  "mkdocstrings~=0.22.0",
  "markdown-exec[ansi]~=1.6.0"
]
