# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

env:
    UV_LOCKED: 1

tasks:
    ########################
    # DEFAULT TASK
    ########################
    default:
        desc: List Available Tasks
        cmds:
            - task --list-all --sort alphanumeric
        silent: true
    ########################
    # INSTALL AND DEPENDENCIES
    ########################
    install:
        desc: Install Project + Dev Dependencies
        cmds:
            - task: pre-commit-install
            - task: sync
    ########################
    # TESTING
    ########################
    test:
        desc: Run Copier Tests
        cmds:
            - uv run -- pytest tests/test_copier.py {{.CLI_ARGS}}
        deps:
            - task: sync
              vars:
                  UV_PYTHON: "{{.UV_PYTHON}}"
                  CLI_ARGS: --quiet
        env:
            UV_PYTHON: "{{.UV_PYTHON}}"
    ########################
    # DOCUMENTATION AND COMMANDS
    ########################
    docs:
        desc: Run Documentation Site
        cmds:
            - uv run --group docs -- mkdocs {{.CLI_ARGS | default "serve"}}
    #######################################
    run:
        desc: Run Project Command (requires "--")
        interactive: true
        cmds:
            - uv run -- {{.CLI_ARGS}}
    ########################
    # DEPENDENCY MANAGEMENT
    ########################
    lock:
        desc: Regenerate Project Lockfile
        cmds:
            - uv lock
        env:
            UV_LOCKED: "0"
    ########################
    # GENERATED PROJECT FIXTURE
    ########################
    example-project:
        desc: Regenerate Example Project
        cmds:
            - rm -rf tests/example-project
            - uv run -- copier copy --vcs-ref=HEAD --defaults --data-file tests/answers.yml . {{.CLI_ARGS | default "tests/example-project"}}
    ########################
    # INTERNAL TASKS
    ########################
    sync:
        desc: Install Project Dependencies
        internal: true
        cmds:
            - uv sync --all-extras {{.CLI_ARGS}}
        env:
            UV_PYTHON: "{{.UV_PYTHON}}"
    #######################################
    pre-commit-install:
        desc: Install Pre-Commit Hooks
        internal: true
        cmds:
            - cmd: |
                  if [ "{{.CI | default 0}}" = "0" ]; then
                      uv tool run --isolated pre-commit install --install-hooks
                  fi
              silent: true
        status:
            - test ! -f {{.ROOT_DIR}}/.pre-commit-config.yaml
